tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
    - name: Web App
      description: The main application web server
      port: 80
      onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mikestead.dotenv
    - DEVSENSE.phptools-vscode
    - EditorConfig.EditorConfig
    - amiralizadeh9480.laravel-extra-intellisense
    - ryannaddy.laravel-artisan
    - onecentlin.laravel5-snippets
    - onecentlin.laravel-blade
    - redhat.vscode-yaml